<?php
/**
 * Something Digital
 *
 * Permission is hereby granted, free of charge, to any person obtaining a copy of
 * this software and associated documentation files (the "Software"), to deal in the
 * Software without restriction, including without limitation the rights to use, copy,
 * modify, merge, publish, distribute, sublicense, and/or sell copies of the Software,
 * and to permit persons to whom the Software is furnished to do so, subject to the
 * following conditions:
 *
 * The above copyright notice and this permission notice shall be included in all copies
 * or substantial portions of the Software.
 *
 * @package     SomethingDigital_BackToTop
 * @author      Brandyn Bold <brandynbold@gmail.com>
 * @copyright   Copyright (c) 2015 Something Digital
 * @license     https://opensource.org/licenses/MIT  The MIT License (MIT)
 */
?>

  <a href="#" id="back-to-top" class="back-to-top">
    <span class="back-to-top__up-arrow">
      <svg viewBox="0 0 44 44" class="sd-icon glyph">
        <use xmlns:xlink="http://www.w3.org/1999/xlink" xlink:href="<?php echo $this->getSkinUrl('images/somethingdigital/back-to-top.svg'); ?>"></use>
      </svg>
    </span>
    <?php echo $this->helper('sd_backtotop')->getText(); ?>
  </a>
