<?php
/**
 * Something Digital
 *
 * Permission is hereby granted, free of charge, to any person obtaining a copy of
 * this software and associated documentation files (the "Software"), to deal in the
 * Software without restriction, including without limitation the rights to use, copy,
 * modify, merge, publish, distribute, sublicense, and/or sell copies of the Software,
 * and to permit persons to whom the Software is furnished to do so, subject to the
 * following conditions:
 *
 * The above copyright notice and this permission notice shall be included in all copies
 * or substantial portions of the Software.
 *
 * @package     SomethingDigital_BackToTop
 * @author      Brandyn Bold <brandynbold@gmail.com>
 * @copyright   Copyright (c) 2015 Something Digital
 * @license     https://opensource.org/licenses/MIT  The MIT License (MIT)
 */
?>

<script type="text/javascript">
  var BackToTopConfig = {};
  BackToTopConfig.speed = <?php echo $this->helper('sd_backtotop')->getScrollSpeed(); ?>;
  BackToTopConfig.persist = "<?php echo $this->helper('sd_backtotop')->getPersistMethod(); ?>";
</script>
